sonar.projectKey=notes-app
sonar.projectName=Notes App
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src,frontend/src
sonar.tests=backend/test,frontend/test

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.js,**/*.test.jsx
sonar.test.inclusions=backend/test/**/*.test.js,frontend/test/**/*.test.js,frontend/test/**/*.test.jsx
sonar.coverage.exclusions=**/test/**,**/*.test.js,**/*.test.jsx
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info